# Generated by Django 4.2.5 on 2023-10-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_payment_id_intent_payment_id_method_payment_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='version',
            field=models.CharField(default=1, max_length=50, verbose_name='версия подписки'),
        ),
    ]
